-- Oracle trade log table for this bot
-- 기본 테이블명: BOT_TRADES (ORACLE_TABLE 로 변경 가능)

CREATE TABLE BOT_TRADES (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TS_UTC TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  SYMBOL VARCHAR2(30) NOT NULL,
  SIDE VARCHAR2(8) NOT NULL,
  PRICE NUMBER(20, 8),
  AMOUNT NUMBER(20, 8),
  REASON VARCHAR2(50),
  MODE VARCHAR2(10),
  ORDER_ID VARCHAR2(100)
);

CREATE INDEX BOT_TRADES_TS_IDX ON BOT_TRADES (TS_UTC);
